### ISSUE TITLE
The time used to test a image

### ISSUE THREAD

**Issue by yezhanglang** [zsyzzsoft/co-mod-gan#12]
This is a really great job! However, when I run the run_generator.py script, It takes more than 20s to test a image. Is that normal?

**Comment by yezhanglang** [comment]
By the way, I use png image to test. And my gpu has 9G video memory.

**Comment by yezhanglang** [comment]
And I modify the run_generator.py script to test a directory of images, after test some images, it keeps OOM.

**Comment by zsyzzsoft** [comment]
The script includes TensorFlow initialization, network loading and compiling, which in all take quite long. If you have multiple images, you should only include [these lines](https://github.com/zsyzzsoft/co-mod-gan/blob/06e3cdeec685f5a4d1e62370fda96bbd810a86b0/run_generator.py#L15-L20) in a `for` loop.

**Comment by yezhanglang** [comment]
I see, it's my fault! I haven't check it carefully. 
Thank you so much! 
感谢大佬！
