### ISSUE TITLE
dockerfile parse error

### ISSUE THREAD

**Issue by josephrocca** [zsyzzsoft/co-mod-gan#21]
Very cool project - thanks for releasing your code! Just a heads up that the readme says:

> We also provide a Dockerfile for Docker users.

But the Dockerfile in the repo is an empty text file.

**Edit**: Actually it's a binary file as mentioned by zsyzzsoft, below.

**Comment by zsyzzsoft** [comment]
I think it has content but GitHub cannot display it as it is a binary file. Can you download it and try it with Docker?

**Comment by josephrocca** [comment]
@zsyzzsoft Yep I tried and it gave this error:
```
Error response from daemon: dockerfile parse error line 1: unknown instruction:
```
The Dockerfile from the stylegan repo (below) works fine for inference - I haven't tried training yet.
```
FROM tensorflow/tensorflow:1.14.0-gpu-py3
RUN pip install scipy==1.3.3
RUN pip install requests==2.22.0
RUN pip install Pillow==6.2.1
```

**Comment by zsyzzsoft** [comment]
I'll check it :)

**Comment by zsyzzsoft** [comment]
Should be fixed now.

**Comment by josephrocca** [comment]
Great, thanks again for releasing this! It's really fun to play around with :)

**Comment by LigZhong** [comment]
@zsyzzsoft Hello，thanks for your great job, I clicked the link to the DockerFile but it seems to be unavailable now. Could you check it? Thanks.
