### ISSUE TITLE
How to control style truncation?

### ISSUE THREAD

**Issue by windj007** [zsyzzsoft/co-mod-gan#22]
Hi! Thank you for releasing this! Really amazing results!

I'm trying to evaluate the model on my data and I'm curious, if there is a way to tune truncation trick in `run_generator.py`? I'd like to buy as much quality as possible and I'm not very interested in diversity.

Should I pass something as input to [Gs.run](https://github.com/zsyzzsoft/co-mod-gan/blob/master/run_generator.py#L16)?

**Comment by zsyzzsoft** [comment]
Yes, pass `truncation_psi=xxx` to `Gs.run`. You can try the updated code which adds an option of `--truncation`.

**Comment by windj007** [comment]
Thank you for the quick answer!

Am I right that `truncation_psi=0` should give the best possible quality? Or I should grid-search for the best value?

**Comment by zsyzzsoft** [comment]
I would recommend the default value. Setting it to less than 1 will not likely have positive effect though I haven't tried it.

**Comment by windj007** [comment]
I've just tried 0.1 and got approximately same metrics, sometimes a bit better, sometimes a bit worse. The difference in FID was about 0.03, compared to CoModGAN with truncation = 1.

**Comment by windj007** [comment]
Thank you for your help!
