### ISSUE TITLE
How to make custom pix2pix dataset and training

### ISSUE THREAD

**Issue by SwordBearFire** [zsyzzsoft/co-mod-gan#24]
Hi, 

Thanks for your impressive code.

I meet a problem about pix2pix when I try to use co-mod-gan to train my dataset. Could you tell me how to make custom pix2pix dataset that can be used in the program. Thank you very much.

sincerely yours
Bell

**Comment by zsyzzsoft** [comment]
Maybe I will publish the pix2pix code in the next week. Basically you can make each image contain 6 channels, first three channels of the output image followed by three channels of the condition image.

**Comment by SwordBearFire** [comment]
> Maybe I will publish the pix2pix code in the next week. Basically you can make each image contain 6 channels, first three channels of the output image followed by three channels of the condition image.

Got it! thank you so much, I have fixed the code, and is training now, thank you again!
