### ISSUE TITLE
About quantitative metric?

### ISSUE THREAD

**Issue by z2liudake** [zsyzzsoft/co-mod-gan#38]
Hi, I have some doubt about the calculation of numerical metric.
1. Your model(co-mod) is trained on 512*512 resolution image, and DeepFillv2(offical) is trained on 256*256 resolution. So in this different resolution situation, how do you calculate the metric(like fid)? 
      a.the deepfillv2(offical) receive 256*256 masked image, and you resize the model's output image to 512*512?
      b.the deepfillv2(offical) receive 512*512 masked image?
      c.other method?
2. DeepFillv2(retrained) model's input image resolution, 256*256 or 512*512?
3. Figure 18 in your paper displays some 1024*1024 resolution images. Do you inference 1024*1024 resolution image directly on co-model which is trained on 512*512 setting?

**Comment by zsyzzsoft** [comment]
1. The model receives 512x512 input.
2. The model is retrained with 512x512 images.
3. They are produced by a separate model trained with 1024x1024 image.

**Comment by z2liudake** [comment]
Thank you!
