### ISSUE TITLE
Use of Normalization Layers in Encoder

### ISSUE THREAD

**Issue by hamzapehlivan** [zsyzzsoft/co-mod-gan#48]
Hi, 

First of all, thanks for sharing this great work!

My question is about using normalization blocks (batch norm, instance norm, etc.) in the Encoder. I did not find any normalization layer when I investigated the source code. Is this really the case, or am I missing something?

If this is the case, is there any particular reason to omit it?

**Comment by zsyzzsoft** [comment]
The use of normalization layers in GAN is somewhat tricky. We just find it good enough without using normalization layers in the encoder, while I also believe that some proper use of normalization layers may further enhance the performance.

**Comment by hamzapehlivan** [comment]
Thanks for the kind response!
