### ISSUE TITLE
Require about ANHIR

### ISSUE THREAD

**Issue by zbw-ai** [zsyzzsoft/co-mod-gan#5]

**Comment by zsyzzsoft** [comment]
It is based on our [recursive-cascaded-network repo](https://github.com/microsoft/Recursive-Cascaded-Networks) but the exact code and model used in the challenge will not be open sourced. Please contact me in that repo or via email if there are any other questions.

**Comment by zbw-ai** [comment]
Thankyou for your reply.What I need is the results of registration in this ANHIR dataset(which means paired images for different stains).Can you share the whole results in the challenge? Thanks.

**Comment by shengyu-ponyai** [comment]
I don't have such results either. All available informations are on the ANHIR website.

**Comment by zsyzzsoft** [comment]
I don't have such results either. All available informations are on the ANHIR website.

**Comment by zbw-ai** [comment]
Thankyou all the same.
